- adr/0008-code-owners.md
Following the discussion on the ADR in issue #287, I've written up the following ADR.
I've done my best to incorporate all the feedback received in a way that:
- We get clarity on the definition of code ownership on an integration.
- Requiring code ownership in a lot of cases, but still, have enough room for current code owners and code reviewers to omit the requirement.
- Allowing small, low-impact and bug fix contributions, without requiring code ownership.
Closes #287
> Adds ADR 0008: Code owners

- .github/ISSUE_TEMPLATE.md
We should never change the architecture of the backend because of bugs in the frontend. This PR adds a line to the issue template to point people at opening frontend issues instead.
> Add sentence to clarify that architecture issues should not be driven by frontend bugs

- adr/0005-code-formatting.md
In home-assistant/home-assistant#29739, we have added `isort` to both our CI and to the pre-commit hooks.
This PR updates ADR-0005 to reflect that.
> Update ADR-0005, add isort

- adr/0010-integration-configuration.md
Home Assistant has been relying on YAML for its configuration format for a long time. However, in certain cases, this caused issues or did not work at all.
This ADR is to protect project goals and to provide clarity to our users and contributors by settings new rules on how integrations need to be configured.
> ADR-0010 - Integration configuration

- adr/0011-discovery-requires-unique-id.md
To protect project goals and to provide clarity to our users and contributors,
we're introducing the following rules on how discoverable integrations need to be designed:
- Integrations that are discoverable must provide an unique id (via `async_set_unique_id`) 
to allow the user to ignore the discovered config entry.
These rules apply to all new integrations. Existing integrations should be reviewed 
for possible ways to improve identification during discovery.
> ADR-0011 - Discovery Requires Unique ID

- adr/0014-home-assistant-supervised.md
Add an ADR for adding Home Assistant Supervised as a supported installation method as defined in #392.
> ADR: Home Assistant Supervised as supported installation method

- adr/0013-home-assistant-container.md
Add an ADR for adding Home Assistant Container as a supported installation method as defined in #392.
> ADR: Home Assistant Container as supported installation method

- adr/0015-home-assistant-one.md
This method was previously known as "Home Assistant". Feedback said this was causing confusion so defining this installation method should also rename it. I put in HA One but if someone thinks of a better name, let's discuss.
>  ADR: Home Assistant OS as supported installation method

- adr/0016-home-assistant-core.md
And finally, the last one :)
Initially I was planning on redirecting users that want to try this installation method to the developer documentation. However, the dev docs talk about cloning the repository versus HA Core which is installed from PyPI. Therefore I have removed that clause.
> ADR-16: Home Assistant Core installation method

- adr/0014-home-assistant-supervised.md
Changes the required version of NetworkManager to match that available in Debian 10 (buster), since 1.18.0 is not. Since supervisor reports no errors running with 1.14.6, this should be a harmless change, and eliminates confusion in diagnosing such errors, as seen here - https://community.home-assistant.io/t/networkmanager-1-18-0-on-debian-buster/223968 - and in issue #427 .
> Adjust required version of NetworkManager

- adr/0014-home-assistant-supervised.md
Future of https://github.com/home-assistant/supervised-installer/pull/126
Is not needed with new NetworkManager settings and Supervisor. Maybe next year we can inform people if they not use systemd-resolvd (default) on Debian.
> Remove Avahi

- adr/0004-webscraping.md
We've seen more and more integrations struggle with ADR004. The problem they struggle with is not that the data fetching is based on scraping, but that some parts of the authentication flow requires extraction of the form fields and their values. Fetching data should happen via an API. We will be more flexible, and hinder less integrations, if we allow integrations to extract forms during the authentication flow. 
That's why I want to propose that we amend ADR004 to allow web scraping of forms during the authentication phase. For robustness, integrations should fetch all fields of the form and not individually extract values of fields in the form. These are less likely to change.
Please limit discussion in this PR to this change. Discussing the ADR004 or other amendments is out of scope …
> Amend ADR004 to allow extracting forms during the auth phase

- adr/0003-monitor-condition-and-data-selectors.md
Current link points to outdated developers doc location.
I pointed to the subsection specifically about `entity_registry_enabled_default`, but we could also consider just pointing to the whole page.  It would be less specific to point to the whole page, but more robust to changes in the structure within the page.
> Fix broken link to dev docs.

- README.md
Not sure if `Discussions` is here to stay, but for now it would be good to change this link in the readme. Since the link is directly to the new issue page, you won't see the pinned issue (https://github.com/home-assistant/architecture/issues/496).
> Change guidance from issue to discussion in README

- adr/0014-home-assistant-supervised.md
Updates the ADR that lists the requirements for Home Assistant Supervised installations.
Marks Debian 11 supported, removes Debian 10 as it is deprecated to keep documentation current and reflect what users should be running.
ℹ️  This PR correctly targets the `current` branch, as the Supervisor is released independently of Home Assistant Core.
⚠️ Should not be merged until the related Supervisor is released to stable
After the deprecation period for Debian 10 has been passed, we can look at bumping other dependencies to have a higher minimum requirement.
Supervisor PR: https://github.com/home-assistant/supervisor/pull/3066
> Update Supervised supported OS

- adr/0009-translations-2.0.md
Link is not working any more because hastebin has been aquired by toptal.com.
I think it is okay to just remove it as it is not neccessary to understand the ADR.
If you think it *is* needed, an example of the old API call would need to be hosted on a more reliable url (maybe in this repo?).
> Remove broken link in translations adr

- adr/0019-GPIO.md
There were two inconsistent spellings of "I2C". Plus shouldn't the date be today as this ADR was approved and merged today?
> 0019 GPIO: Spelling consistency plus final approval date correction

- adr/0010-integration-configuration.md
This is a small update to ADR010 to remove the implementation detail of how UI-based configuration is stored in the backend (previously: config flow, storage collection).
> Loosen requirement in ADR10 how UI-based configuration is stored

- adr/0002-minimum-supported-python-version.md
Clarifies Python version requirements as per the discussion in home-assistant/core#86807
We try to support latest 2 python versions.
> Update Python version requirements

- adr/0014-home-assistant-supervised.md
For now I have removed Debian Bullseye and added Bookworm as it is already implied the Bullseye is still supported for 4 months, Although I am not sure if I should add both 
Link to Supervisor PR: https://github.com/home-assistant/supervisor/pull/4377
Link to Supervised Installer PR: https://github.com/home-assistant/supervised-installer/pull/297
> Update ADR to support Debian 12 Bookworm

- adr/0015-home-assistant-os.md
Add Home Assistant Yellow/Green to supported boards list. Also add ODROID-C4 and ODROID-M1.
Mention generic x86-64 support.
Also clarify virtualization support a bit and sort lists alphabetically.
> Update supported boards

- adr/0018-supported-databases.md
Since we do not test against older versions of SQLite, they are a terrible user experience, and we keep [finding problems](https://github.com/home-assistant/core/pull/104296)
Update the minimum SQLite version to 3.40.1 which is the bookworm version
core PR proposes 2025.2 as the removal date for the old version https://github.com/home-assistant/core/pull/104298
> Update minimum supported SQLite version to 3.40.1

- adr/0015-home-assistant-os.md
Updating the outdated list of targets to current state which the support stabilized at without any prior architecture discussion.
Commenting on individual changes:
- On Yellow we rolled out official support for CM5 in HAOS 14. There was no architecture discussion on this and we should keep it in mind for the future. This is just reflecting the current state.
- Similar for RPi 5 - we started to support it without any change here.
- "Tinkerboard" was too vague, we don't support all models, so clarifying on the actual models currently supported.
- N2+ is just a variation of N2, N2 is discontinued but can be interchanged easily with only a difference in the device tree. Explicitly adding also the N2+ to avoid confusion.
- ODROID-M1S is officially supported for a while through a community …
> Update ADR-0015: sync list of supported targets with reality

- adr/0015-home-assistant-os.md
In #1189 Khadas VIM3 was unintentionally left out from the list of supported boards. Its support was added and maintained since home-assistant/operating-system#1473, so this is just another sync with the reality.
> Update ADR-0015: add already supported Khadas VIM3 to the list
